language: python

python:
  - 3.6

notifications:
  email:
    on_success: change
    on_failure: change

install:
  - pip install -r requirements.txt
  - pip install pycodestyle

script:
  - pycodestyle --count --show-source --exclude=src/ECS .
